[build-system]
requires = ["setuptools>=65", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "OctoprintBrickWeave"
version = "0.1.1"
description = "BrickWeave plugin for OctoPrint"
readme = "README.md"
requires-python = ">=3.13,<4"
authors = [
    {name = "Justin Ahrens", email = "justin@ahrens.net"}
]
license = {text = "MIT"}
dependencies = ["octoprint"]

[project.urls]
Homepage = "https://github.com/OpenSourceModular/BrickWeave"
